- name: Make sure no other OAK applications/services are running.
  command: "{{ venv_oak }} a d"

- name: Clear any containerd images (ctr)
  command: "{{ venv_oak }} w ctr delete-images"
  when: clear_containerd_images
