- include_role:
    name: prepare_oak_cli

- name: Clean up before starting the experiments
  command: "{{ venv_oak }} eval localhost clean"

- name: "Handle all '{{ number_of_experiment_runs }}' experiments"
  include_tasks: handle_experiment.yml
  vars:
    experiment_id: "{{ item }}"
  with_sequence: start=1 end="{{ number_of_experiment_runs }}"

