- include_tasks: set_init_vars.yml

- include_role:
    role: prepare_oak_cli
  when: is_cluster or is_root

- include_tasks: clean_up_before_evaluation_cycle.yml

- name: "Handle all '{{ number_of_evaluation_runs }}' evaluations"
  include_tasks: handle_evaluation_run.yml
  vars:
    evaluation_run_id: "{{ item }}"
  with_sequence: start=1 end="{{ number_of_evaluation_runs }}"
