- pause:
    seconds: 3


- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "Project Start"
- name: Trigger FLOps Project
  command: "{{ venv_oak }} addon flops p mnist_sklearn_large"
- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Create new FLOpsProject application"


- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Deploy FLActorsImageBuilder"
- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "FL-Actors Image Build"
- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Undeploy FLActorsImageBuilder"


- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Start handling FL training processes"
- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "FL Training"
- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Aggregator successfully finished training"


- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Start handling FL post training"
- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "Start Post-Training Steps"


- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Deploy TrainedModelImageBuilder"
- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "Trained-Model Image Build"
- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Undeploy TrainedModelImageBuilder"


- include_tasks: wait_for_flops_project_stage.yml
  vars:
    stage_indicator: "Deploy TrainedModel"
- include_tasks: handle_new_stage.yml
  vars:
    stage_name: "Deploy Trained-Model"
- include_tasks: check_trained_model_service.yml
- pause:
    seconds: 5
- include_tasks: check_trained_model_service.yml
