name: Python Codestyle Check (ruff)

on: [push, pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check
